[package]
name = "edge-lqip"
version = "0.1.0"
authors = []
edition = "2018"
publish = false

[profile.release]
debug = 1

[dependencies]
fastly = "^0.8.2"
image = { version = "0.23.14", default-features = false, features = ["png", "jpeg"] }
blurhash = "0.1.1"
